CREATE TABLE department (
	`id` BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '部门名称或下属机构名称',
	`level` VARCHAR(255) NOT NULL DEFAULT '0' COMMENT '部门级别字符串',
	`parent_id` BIGINT UNSIGNED NOT NULL COMMENT '父级主键id',
	`seq` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序号',
	`mtime` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间',
	`ctime` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间',
	`muser_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '修改人',
	`cuser_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
	PRIMARY KEY(`id`),
KEY `idx_level` (`level`)
)ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '部门架构表';